version: 0.0
os: linux

files:
  - source: app
    destination: /home/ec2-user/webapp

permissions:
  - object: /home/ec2-user/protect
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    type:
      - file

hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 10
      runas: ec2-user